Don't error on bumping Microsoft Go version with no changes
This commit fixes an issue where the updatecli bump for the Microsoft Go version
errors out when there are no git changes to the Dockerfiles, displaying:

```
update-go-versions
------------------
The shell 🐚 command "/bin/sh /tmp/updatecli/bin/85e65467bf89c2d94fa810c3870bcec2cffb0692ebf098263381494a59442bfe.sh" ran successfully with the following output:
----
Update go version 1.23.10-1
----
⚠ - ran shell command ".github/updatecli.d/bump-go-microsoft-version.sh 1.23.10-1"

ERROR: something went wrong in target "update-go-versions" : "no changed file to commit"

Pipeline "Bump golang-microsoft to latest version" failed
Skipping due to:
	targets stage:	"something went wrong during target execution"

ACTIONS
========

ERROR: 1 target(s) (update-go-versions) failed for action "default"
```