Fix segfauls and libpcap compilation errors
This commit fixes libpcap related compilation errors like:

```
./gencode.c:4914:13: error: 'cstate' undeclared (first use in this function)
```

by switching to a newer version of libpcap (from 1.8.1 to 1.10.4).
Additionally it resolves Segfaults in CI by using an instance type with
more memory, and finally, improves discoverability and memory usage by
switching to ubuntu 24.04 based CI images.